- name: Install Docker on web servers
  hosts: all
  become: yes

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true